"""Caller (NPC) models."""

from datetime import datetime
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field
from bson import ObjectId

from src.models.game import PyObjectId


class CallerModel(BaseModel):
    """
    Caller/NPC model.

    START HERE:
    1. Represents an individual who can call the radio
    2. Generated by AI or pre-scripted
    3. Stores personality, backstory, relationship with player
    4. Stored in MongoDB 'callers' collection
    5. Can evolve over time (status changes, secrets revealed)
    """

    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    game_id: PyObjectId
    caller_id: str  # unique identifier like "caller_001"
    name: Optional[str] = None  # May be unknown initially
    voice_description: str = "distorted"  # raspy, child-like, calm, panicked
    first_contact_night: int
    call_count: int = 0
    status: str = "unknown"  # alive, dead, infected, unknown, entity
    personality_traits: List[str] = Field(default_factory=list)
    backstory: str = ""
    location: Optional[str] = None
    relationship_score: float = 0.0  # -100 to +100
    secrets: List[str] = Field(default_factory=list)  # Revealed over time
    is_hostile: bool = False
    trust_level: float = 0.0
    last_seen_night: int = 0
    metadata: Dict[str, Any] = Field(default_factory=dict)

    class Config:
        populate_by_name = True
        arbitrary_types_allowed = True
        json_encoders = {ObjectId: str}
